spring.application.name=api.aftercare

server.port=8082

# Datasource configuration
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/aftercaredb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Email
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Customized email properties
email.sender.host=smtp.gmail.com
email.sender.port=587
email.sender.username=bunsenplus.org@gmail.com
email.sender.password=htelkmzmeefbulkv
email.sender.resetPasswordUrl=http://localhost:3000/reset-password

