spring.application.name=api.aftercare
spring.profiles.active=dev
server.port=8082

# Datasource configuration for H2
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/db

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
aftercare.app.jwtSecret=aftercareSecretKey4939318507AbcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
aftercare.app.jwtExpirationMs=86400000