spring.application.name=api.aftercare
server.port=${SPRING_PORT}
# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Email
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.timeout=5000
spring.mail.properties.mail.smtps.connectiontimeout=5000

# Customized email properties
email.sender.host=${SPRING_EMAIL_SENDER_HOST}
email.sender.port=${SPRING_EMAIL_SENDER_PORT}
email.sender.username=${SPRING_EMAIL_SENDER_USERNAME}
email.sender.password=${SPRING_EMAIL_SENDER_PASSWORD}

email.sender.resetPasswordUrl=${SPRING_EMAIL_SENDER_RESET_PASSWORD_URL}
email.sender.baseUrl=${SPRING_EMAIL_SENDER_BASE_URL}

google.oauth.client-ids=${SPRING_GOOGLE_OAUTH_CLIENT_IDS}
google.clientId=${SPRING_GOOGLE_CLIENT_ID}
google.clientSecret=${SPRING_GOOGLE_CLIENT_SECRET}
google.redirectUri=${SPRING_GOOGLE_REDIRECT_URI}

# Production settings
spring.datasource.driver-class-name=org.postgresql.Driver

# Will be overridden by environment variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Connection pooling
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# Memory optimization
spring.jpa.properties.hibernate.jdbc.batch_size=5
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
spring.main.lazy-initialization=true

# Enable health endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT Configuration
aftercare.app.jwtSecret=${SPRING_APP_JWT_SECRET}
aftercare.app.jwtExpirationMs=${SPRING_APP_JWT_EXPIRATION_MS}
aftercare.app.jwtRefreshExpirationMs=${SPRING_APP_JWT_REFRESH_EXPIRATION_MS}
aftercare.app.verificationTokenExpirationMs=${SPRING_APP_VERIFICATION_TOKEN_EXPIRATION_MS}
